UNAME_M := $(shell uname -m)
PLATFORM := Linux-$(UNAME_M)

PREFIX = $(CURDIR)/_install/$(PLATFORM)
BUILD_DIR = $(CURDIR)/build/$(PLATFORM)
DIST_DIR = $(CURDIR)/dist
PKG_DIR = $(DIST_DIR)/$(APP)-$(VERSION)-$(PLATFORM)

RPATH := -Wl,-rpath,'$$ORIGIN/../lib'
HTS_LIB := $(PREFIX)/lib/libhts.so
PACKAGE_TAR := $(PKG_DIR).tar.gz

include Makefile.common

package: all
	rm -rf $(PKG_DIR)
	mkdir -p $(PKG_DIR)/bin
	mkdir -p $(PKG_DIR)/lib
	cp $(BUILD_DIR)/$(APP) $(PKG_DIR)/bin/
	cp -a $(PREFIX)/lib/libhts.so* $(PKG_DIR)/lib/ 2>/dev/null || true
	tar -czf $(PACKAGE_TAR) -C $(DIST_DIR) -- $(notdir $(PKG_DIR))