/* Default config.h generated by Makefile */
#ifndef _XOPEN_SOURCE
#define _XOPEN_SOURCE 600
#endif
#define HAVE_LIBBZ2 1
#define HAVE_LIBLZMA 1
#ifndef __APPLE__
#define HAVE_LZMA_H 1
#endif
#define HAVE_DRAND48 1
#define HAVE_LIBCURL 1
#if defined __x86_64__ && (defined HAVE_SSSE3 || defined HAVE_AVX2 || defined HAVE_AVX512)
#define HAVE_X86INTRIN_H 1
#endif
#if defined __x86_64__ || defined __arm__ || defined __aarch64__
#define HAVE_ATTRIBUTE_CONSTRUCTOR 1
#endif
#if defined __linux__
#define HAVE_GETAUXVAL
#elif defined __FreeBSD__
#define HAVE_ELF_AUX_INFO
#elif defined __OpenBSD__
// Enable extra OpenBSD checks (see simd.c)
#define HAVE_OPENBSD
#endif
